### ISSUE TITLE
Testing with ahven 2.6 fails

### ISSUE THREAD

**Issue by RREE** [onox/json-ada#1]
There are two issues when running "make build_unit_tests":

1. There is no "ahven.gpr" in ahven-2.6. I had to set it to 
`with "<path-to-ahven>/gnat/ahven_lib"`
2. During the link step I get the following error:
   gnatbind test_bindings.ali
   error: "test_bindings.adb" has restriction No_Recursion
   error: but the following files violate this restriction:
   error:   "ahven-listeners-basic.adb"
   error:   "ahven-results.adb"
   error:   "ahven-xml_runner.adb"
   gprbind: invocation of gnatbind failed
   gprbuild: unable to bind test_bindings.adb

**Comment by onox** [comment]
Issue 1 is an external issue and should be fixed in the main branch of Ahven. See https://bitbucket.org/tkoskine/ahven/issues/12/make-install-does-not-install-a-gpr-file#comment-42790389

For issue 2 I'll push a fix shortly.
