### ISSUE TITLE
Makefile does not work on Windows

### ISSUE THREAD

**Issue by RREE** [onox/json-ada#2]
In the top of your Makefile in line 5 you set LDFLAGS to values that are specific to GNU ld and that only work on Linux. I had to comment that line in order to build the unit tests

**Comment by onox** [comment]
@RREE How did you get the `make` tool on Windows? I don't have it via GPS or git-bash.

**Comment by RREE** [comment]
I either use Cygwin or MSys. Both provide a more or less Unix 
environment on Windows.

RREE

Am 07.12.2018 um 18:51 schrieb onox:
