### ISSUE TITLE
Building fails with GNAT CE 2020

### ISSUE THREAD

**Issue by kyle-vasilia** [onox/json-ada#7]
Hello! I'm using the latest version of GNAT CE and mingw32-make to build this project and I'm errors from json-types and json-parsers 

>json-types.adb:135:28: non-local pointer cannot point to local object
>json-types.adb:146:28: non-local pointer cannot point to local object
>json-parsers.adb:152:25: non-local pointer cannot point to local object

This is the way it's compiling
> gprbuild -dm -p -P tools/json_ada.gpr -cargs -O2 -march=native

Will mess with code and see if I can get anywhere, but I'm new to ADA and I'm not sure if this is a platform specific bug or if I'm doing something wrong!

Cheers!

**Comment by onox** [comment]
:open_mouth: 

Did you try this with GNAT CE 2020? Does it happen in GPS (GNAT Studio) as well?

I don't have GNAT CE atm, but I don't get those errors in GCC 10.1 (which is very recent). I'll try to install CE and set up a Github Action workflow this weekend. In the mean time, as a workaround, you can replace `'Access` with `'Unchecked_Access` on those 3 lines.

**Comment by onox** [comment]
I just ran gprbuild in a Docker container with GNAT CE 2020 and I get the mentioned errors as well.
